openapi: '3.0.2'
info:
  description: 
    'This is a Final Project for Advancing Career Program Alterra Academy.'
  version: "1.0.0"
  title: Alta Store API Documantation
  contact:
    email: dev@alta.store.com
servers:
  - url: http://ec2-54-255-28-193.ap-southeast-1.compute.amazonaws.com:8080/v1
  - url: http://ec2-54-255-28-193.ap-southeast-1.compute.amazonaws.com:8080/
tags:
  - name : Admins
    description: ""
  - name : Products
    description: ""
  - name : Categories
    description : ""
paths:
   

   /admins:
      post:
        tags:
          - "Admins"
        summary: Create new admins
      get:
        tags:
          - "Admins"
        summary: Get all data admins
      put:
        tags:
          - "Admins"
        summary: Update data admins
      delete:
        tags:
         - "Admins"
        summary : Delete data admins

components:
   schemas:
    Response:
      type: object
      properties:
        code:
          type: string
          description: Code Message from server
        message:
          type: string
          description: Message from server
        data:
          description: Data that client requested
          type: object
         
          
      
