name: ci/cd process

on:
  push:
    branches:
      - 'Admin'
jobs:
  unit-test:
      name: unit-test-ci
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16
      - name: running unit unit-test
        run: go test ./... -cover

  build-push-docker:
    name: build image and push registry docker hub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
     - uses: actions/checkout@v2
     - name: generate config file
       env:
        CONFIG: ${{secrets.CONFIG_APP}}
       run: |
         echo "$CONFIG" > ./.env 
     - name: build image
       run: docker build -t mhakim/altastore:1.4 .
     - name: login docker hub
       uses: docker/login-action@v1
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: push to docker hub
       run: docker push mhakim/altastore:1.4
    
  deployment-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2 
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/hakim.pem
          chmod 400 ~/.ssh/hakim.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/hakim.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) || true && docker pull mhakim/altastore:1.4 && docker run -d -p 8080:8080 --name=mycontainer mhakim/altastore:1.4'
       