name: ci/cd process

on:
  push:
    branches:
      - 'dev_thio'

jobs:
  unit-test:
    name: unit_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with: 
        go-version: 1.16
    - name: running unit test
      run: go test ./... -cover 
