name: ci/cd process

on:
  push:
    branches:
      - 'Admin'
jobs:
  unit-test:
      name: unit-test-ci
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with: 
          go-version: 1.16
      - name: running unit unit-test
        run: go test ./... -cover

  build-push-docker:
    name: build image and push registry docker hub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
     - uses: actions/checkout@v2
     - name: generate config file
       env:
        CONFIG: ${{secrets.CONFIG_APP}}
       run: |
         echo "$CONFIG" > ./.env 
     - name: build image
       run: docker build -t mhakim/altastore:1.4 .
     - name: login docker hub
       uses: docker/login-action@v1
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: push to docker hub
       run: docker push mhakim/altastore:1.4
       